export const WEBSITE_DONATION_CATALOG_SEED = [
  {
    slug: "health",
    title: "Health",
    category: "General",
    icon_key: "health",
    price: 5000,
    is_new: false,
    sort_order: 10,
    initiatives: [
      {
        slug: "health-patient-care",
        title: "Patient Care",
        subtitle: "Initiative Per Patient",
        price: 10000,
        description:
          "The per patient cost includes consultancy fees, diagnostic tests, and the cost of medicines",
        duration: "One time",
        icon_key: "health",
        sort_order: 10,
      },
      {
        slug: "health-medical-support",
        title: "Medical Support",
        subtitle: "Initiative Per Beneficiary",
        price: 40000,
        description:
          "Medical Support Initiative provides direct financial assistance — with payments made straight to partner hospitals — for deserving patients who cannot afford essential surgical procedures. This program supports a broad range of surgeries, including gynecological, orthopedic, and other critical medical interventions, ensuring that vulnerable individuals receive timely, safe, and life-enhancing treatment.",
        duration: "One time",
        icon_key: "health",
        sort_order: 20,
      },
      {
        slug: "health-rehabilitation-pwds",
        title: "Rehabilitation of PWDs",
        subtitle: "Per Beneficiary",
        price: 20000,
        description:
          "This initiative focuses on restoring independence and mobility for individuals with physical disabilities or mobility impairments. By providing wheelchairs, crutches, walkers, and other mobility aids, we aim to remove the barriers that limit their access to education, healthcare, employment, and social participation.",
        duration: "One time",
        icon_key: "health",
        sort_order: 30,
      },
    ],
  },
  {
    slug: "education",
    title: "Education",
    category: "General",
    icon_key: "education",
    price: 3000,
    is_new: false,
    sort_order: 20,
    initiatives: [
      {
        slug: "education-scholarship",
        title: "Scholarship",
        subtitle: "Per Student/Per Month",
        price: 15000,
        description:
          "The monthly scholarship for deserving students encompasses various expenses, including tuition fees, accommodation, food, and stationery costs. This comprehensive support aims to alleviate the financial burden on students and ensure their continued access to education.",
        duration: "Minimum 2-years",
        icon_key: "education",
        sort_order: 10,
      },
      {
        slug: "education-dream-school",
        title: "Dream School",
        subtitle: "Per School/Per Month",
        price: 35000,
        description:
          "Dream Schools is a flagship educational initiative designed to bring out-of-school and deserving children back into the learning environment. Each Dream School accommodates 40 students and provides a complete package of support including free books, uniforms, school bags, and shoes, ensuring that no child is deprived of education due to financial barriers.",
        duration: "4-Years Session",
        icon_key: "education",
        sort_order: 20,
      },
      {
        slug: "education-hafiz",
        title: "For Hafiz",
        subtitle: "Per Student/Per Month",
        price: 5000,
        description:
          "The monthly expenses for a Hafiz include various components such as the teacher's salary, operational expenses, and other essential costs associated with their education and well-being.",
        duration: "2-Years Session",
        icon_key: "education",
        sort_order: 30,
      },
      {
        slug: "education-alim",
        title: "For Alim",
        subtitle: "Per Student/Per Month",
        price: 18000,
        description:
          "The monthly expenses for an Alim student typically encompass fees, boarding and lodging costs, as well as food expenses. These components collectively contribute to their educational and living requirements.",
        duration: "6-Years",
        icon_key: "education",
        sort_order: 40,
      },
    ],
  },
  {
    slug: "clean-water",
    title: "Clean Water",
    category: "General",
    icon_key: "clean_water",
    price: 2000,
    is_new: true,
    sort_order: 30,
    initiatives: [
      {
        slug: "clean-water-hand-pump",
        title: "Hand Pump",
        subtitle: "Per Unit",
        price: 90000,
        description:
          "Projects involving hand pumps cater to varying depths of water levels to ensure access to clean water across different regions",
        duration: "One time",
        icon_key: "clean_water",
        sort_order: 10,
      },
      {
        slug: "clean-water-afridev",
        title: "Community Hand Pump",
        subtitle: "Per Unit",
        price: 125000,
        description:
          "The Community Hand Pump is highly recommended for areas with low water levels, as it is specifically designed to efficiently extract water from shallow depths.",
        duration: "One time",
        icon_key: "clean_water",
        sort_order: 20,
      },
      {
        slug: "clean-water-filtration-plant-1",
        title: "Filtration Plant (without construction)",
        subtitle: "Per Unit : Filtration Plant (without construction 2.2 Million)",
        price: 2200000,
        description:
          "This initiative will be carried out with active community participation and contributions. It encompasses all expenses related to the RO filtration plant, excluding civil construction work.",
        duration: "One time",
        icon_key: "clean_water",
        sort_order: 30,
      },
      {
        slug: "clean-water-filtration-plant-2",
        title: "Filtration Plant (with construction)",
        subtitle: "Filtration Plant Per Unit (3.2 Million)",
        price: 3200000,
        description:
          "This initiative will be implemented without community participation or contributions. It covers all expenses related to the Solarized RO filtration plant (fully automated), including solar system, equipment, machinery, and civil construction work.",
        duration: "One time",
        icon_key: "clean_water",
        sort_order: 40,
      },
      {
        slug: "clean-water-solar-pump",
        title: "Solar Submersible Pump",
        subtitle: "Per Unit",
        price: 250000,
        description:
          "For plains areas, the project entails borehole drilling, installation of a submersible pump, utilization of 4 solar panels, and provision of water tanks.",
        duration: "One time",
        icon_key: "clean_water",
        sort_order: 50,
      },
      {
        slug: "clean-water-solar-turbine",
        title: "Solar Submersible Pump / Turbine",
        subtitle: "Per Unit",
        price: 500000,
        description:
          "For desert areas, the initiative comprises borehole drilling, installation of a submersible pump/turbine, construction of room, incorporation of 8 solar panels, and provision of water tanks.",
        duration: "One time",
        icon_key: "clean_water",
        sort_order: 60,
      },
    ],
  },
  {
    slug: "apna-ghar",
    title: "Apna Ghar",
    category: "Sadqa",
    icon_key: "apnaghar",
    price: null,
    is_new: false,
    sort_order: 40,
    initiatives: [
      {
        slug: "apna-ghar-build-home",
        title: "Brick",
        subtitle: "Per Brick",
        price: 1000,
        description:
          "This initiative is aimed at deserving widows and their orphaned children who lack stable housing and basic security. The project provides a safe place to live with dignity.",
        duration: "One time",
        icon_key: "apnaghar",
        sort_order: 10,
      },
    ],
  },
  {
    slug: "disaster-management",
    title: "Gaza Relief",
    category: "General",
    icon_key: "disaster_relief",
    price: 5000,
    is_new: false,
    sort_order: 50,
    initiatives: [],
  },
  {
    slug: "kasb-skill-development",
    title: "KASB Skill Development",
    category: "Sadqa",
    icon_key: "kasb",
    price: 4000,
    is_new: false,
    sort_order: 60,
    initiatives: [
      {
        slug: "kasb-empowering-woman",
        title: "Empowering a Woman",
        subtitle: "Per Beneficiary",
        price: 100000,
        description:
          "This initiative is particularly recommended for woman-headed families to promote sustainable livelihoods.",
        duration: "One time",
        icon_key: "kasb",
        sort_order: 10,
      },
    ],
  },
  {
    slug: "seeds-of-change",
    title: "Seeds of Change",
    category: "General",
    icon_key: "seeds",
    price: 2500,
    is_new: false,
    sort_order: 70,
    initiatives: [
      {
        slug: "seeds-of-change-plant",
        title: "SEEDS OF CHANGE",
        subtitle: "Per Plant",
        price: 750,
        icon_key: "seeds",
        sort_order: 10,
      },
    ],
  },
  {
    slug: "aas-lab-diagnostics",
    title: "Aaslab",
    category: "General",
    icon_key: "aaslab",
    price: 3500,
    is_new: false,
    sort_order: 80,
    initiatives: [],
  },
  {
    slug: "community-services",
    title: "Community Service",
    category: "Sadqa",
    icon_key: "community",
    price: 3000,
    is_new: false,
    sort_order: 90,
    initiatives: [
      {
        slug: "community-feed-family",
        title: "Feed a Family for whole month",
        subtitle: "Per Family",
        price: 8500,
        description:
          "The monthly ration for deserving families includes essential food items necessary for their sustenance. This support helps alleviate food insecurity and ensures that these families have access to nutritious meals on a regular basis.",
        duration: "1-Year",
        icon_key: "community",
        sort_order: 10,
      },
      {
        slug: "community-ramzan-ration",
        title: "Ramadan Ration",
        subtitle: "Per Family",
        price: 9600,
        description:
          "The monthly ration for deserving families includes essential food items necessary for their sustenance. This support helps alleviate food insecurity and ensures that these families have access to nutritious meals on a regular basis.",
        duration: "One time",
        icon_key: "community",
        sort_order: 20,
      },
      {
        slug: "marriage-gift-distribution",
        title: "Marriage Gift",
        subtitle: "Per Benificiary",
        price: 150000,
        description:
          "This initiative is aimed at deserving girls whose families are unable to make arrangements for their marriage, providing them with essential support for their marital journey.",
        duration: "One time",
        icon_key: "community",
        sort_order: 30,
      },
    ],
  },
];
